name: "Algorithm Tasks Submit"
description: "Please submit clear and reproducible optimization tasks according to the template (public code + public dataset)"
title: "[Task] "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        ## Submission Notes (Read First)
        - We only accept **public code** hosted on open-source platforms such as GitHub as the baseline.
        - We only accept tasks optimized on **public datasets**.
        - For requests involving private code/data optimization, please contact: interndiscovery@pjlab.org.cn

  - type: textarea
    id: task_desc
    attributes:
      label: Task Description
      description: Please describe in **one paragraph** what you want to optimize, the goal, the success criteria (preferably quantifiable), and any necessary background information.
      placeholder: |
        Example: On the public dataset X, we want to improve the baseline {metric} from A to B while keeping inference speed no lower than Y. The success criterion is ...
    validations:
      required: true

  - type: input
    id: baseline_repo
    attributes:
      label: Baseline Repository Link (Must be Public)
      description: Only public repository links on open-source platforms such as GitHub are accepted.
      placeholder: "e.g., https://github.com/<org>/<repo>"
    validations:
      required: true

  - type: textarea
    id: baseline_repro
    attributes:
      label: Baseline reproduction (minimal)
      description: "Keep it minimal but reproducible: provide the commit/tag + one key command/step (this is the only 'command' field we keep)."
      placeholder: |
        commit/tag: <fill in>
        run: <one command or minimal steps>
    validations:
      required: true

  - type: input
    id: dataset
    attributes:
      label: Dataset (Must be Public)
      description: Dataset name + official link / download instructions.
      placeholder: "e.g., COCO 2017 https://cocodataset.org/#download"
    validations:
      required: true

  - type: textarea
    id: metrics
    attributes:
      label: Results and Evaluation Metrics
      description: Clearly specify metric definitions, evaluation scripts/commands, and data splits (if any).
      placeholder: |
        Metrics:
        Evaluation command/script:
        Data split:
    validations:
      required: true

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Preconditions (required)
      description: Please confirm that your submission satisfies the following constraints.
      options:
        - label: The baseline I provide comes from **public code** hosted on an open-source platform such as GitHub.
          required: true
        - label: The task I use/optimize is based on a **public dataset**.
          required: true
        - label: If my request involves private code/data, I will contact interndiscovery@pjlab.org.cn by email instead.
          required: true