# InternAgent Configuration
# Comprehensive configuration file with only essential settings

# System Version
version: "1.0.0"

# Model Providers Configuration
models:
  # Default provider used when not specified
  default_provider: "openai"

  # OpenAI Configuration
  openai:
    model_name: "gpt-4o-2024-11-20"
    api_key: ""  # Set via environment variable OPENAI_API_KEY
    max_tokens: 4096
    temperature: 0.7

  # # DeepSeek R1 Configuration (alternative provider)
  # dsr1:
  #   model_name: "DeepSeek-R1"
  #   api_key: ""  # Set via environment variable DS_API_KEY
  #   max_tokens: 4096
  #   temperature: 0.7

# Agent Configuration
agents:
  # Idea Generation Agent
  generation:
    model_provider: "default"
    generation_count: 15
    creativity: 0.7
    do_survey: true
    temperature: 0.9

  # Survey Agent (for literature search)
  survey:
    model_provider: "default"
    max_papers: 50

  # Reflection Agent (for critique and analysis)
  reflection:
    model_provider: "default"

  # Evolution Agent (for idea evolution)
  evolution:
    model_provider: "default"
    creativity_level: 0.6
    temperature: 0.8
    evolution_count: 3

  # Method Development Agent
  method_development:
    model_provider: "openai"  # Use more powerful model
    model_name: "gpt-4o-2024-11-20"

  # Refinement Agent
  refinement:
    model_provider: "openai"
    model_name: "gpt-4o-2024-11-20"

  # Ranking Agent (for idea scoring)
  ranking:
    model_provider: "default"
    criteria:
      novelty: 0.3
      feasibility: 0.4
      impact: 0.2
      clarity: 0.1

  # Scholar Agent (for literature search and relevance)
  scholar:
    model_provider: "default"
    search_depth: "moderate"
    max_papers: 10
    temperature: 0.6

# Workflow Configuration
workflow:
  max_iterations: 4
  top_ideas_count: 5
  top_ideas_evo: true
  max_concurrent_tasks: 5

# Memory/Storage Configuration
memory:
  backend: "file_system"  # Options: file_system, in_memory
  file_dir: "results"

# External Tools Configuration
tools:
  # Web Search
  web_search:
    enabled: true
    provider: "google"
    api_key: ""  # Set via environment variable SEARCH_API_KEY
    max_results: 5

  # Literature Search
  literature_search:
    semantic_scholar_key: ""  # Set via environment variable SS_API_KEY
    max_results: 10

# Logging Configuration (optional)
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "logs/intern_agent.log"
